### ISSUE TITLE
Slider is broken when large images are used

### ISSUE THREAD

**Issue by AlexSkrypnyk** [civictheme/uikit#294]
There are numerous issues with the Slider:

1. Image stretches the Slider height because it is not vertically constrained.
2. The horizontal layout does not follow grid.

<img width="649" alt="Organisms___Slider_-_Slider_⋅_Storybook" src="https://github.com/civictheme/uikit/assets/378794/8725fe0b-8f79-4d3b-a8d5-11e9dd1612d7">

Solution direction:

To solve `#1`, we want the highest of the content or image to drive the height of the Slide. Note that "slider-rail" is calculated based on the tallest slide.

to solve `#2`, we need to update the markup to use the grid classes.

1. Implement `min-height` and `max-height` for the image through variable (see `Campaign` implementation).
2. Implement image-fit to make sure that image dimensions never drive the hight of the Slide
3. Update the horizontal layout to follow the grid (note that figma "almost" follows the grid - we will fix it later). See `Campaign` implementation on the grid.

**Comment by febdao** [comment]
Hi @richardgaunt 
This issue has been fixed, 
Please review and merge the PR https://github.com/civictheme/uikit/issues/294
![Screenshot 2024-10-24 at 3 30 16 PM](https://github.com/user-attachments/assets/d5358b2b-e8d2-4865-a360-bbfa990e8694)
![Screenshot 2024-10-24 at 3 33 33 PM](https://github.com/user-attachments/assets/d3ba1daa-6f3d-49a6-8ef9-d42b3b2e0d0a)
Cheers,

**Comment by AlexSkrypnyk** [comment]
@richardgaunt 
This is still broken
<img width="473" alt="Organisms___Slider_-_Slider_⋅_Storybook" src="https://github.com/user-attachments/assets/2bbfeeb1-56a8-4c79-a27d-c4b09e298f1e">

**Comment by daniel-grynenko** [comment]
Test env: DEV
Overall test status: PASS

Test results:
1. Verified that large images dont stretch the slider height and that min-height and max-height constraints are applied correctly.
2. Checked that small images dont change the way the slider appears.
3. Ensured that the tallest slide determines the overall slider height and that content remains aligned.
4. Validated that images maintain their proportions and do not change the height of the slide.
5. Confirmed that the layout follows the grid system and content is properly aligned on the slider.

Desktop view - Large image:
<img width="1037" alt="Image" src="https://github.com/user-attachments/assets/3fa33cd3-442b-494d-9847-a3657c74c66e" />

Desktop view - Small image:
Small images expectedly do not change the way the sliders appear. Slides with small images will remain the same size as slides with large images.
<img width="1266" alt="Image" src="https://github.com/user-attachments/assets/19f7c1e8-e576-47f0-9fba-9ecba7195288" />

Mobile view - Large image:
<img width="683" alt="Image" src="https://github.com/user-attachments/assets/42b48b88-ab31-44ea-ac2a-a59093e69117" />
